name = "sticker-miniapp"
main = "functions/index.js"
compatibility_date = "2024-12-01"

account_id = "9363690a0f16f29325f426d2bfd6a627"

[vars]
BOT_TOKEN = "8453580045:AAEvTYImiVJc_2xt8bfpXbhUl1PpLypsujo"
ADMIN_ID = "1849257766"

[[kv_namespaces]]
binding = "DB"
id = "55de8c5c17f34e46a34823d199f8aecd"
