name = "stickerminiapp-worker"
main = "src/index.js"
compatibility_date = "2024-06-01"
account_id = "9363690a0f16f29325f426d2bfd6a627"

[[kv_namespaces]]
binding = "KV"
id = "c49ea2d3b31b49f79620c9ae09827a9d"

[[d1_databases]]
binding = "DB"
database_name = "stickerminiapp-db"
database_id = "e0afd8ba-39ee-4271-8431-11e57a8d0851"

[vars]
FRONTEND_URL = "https://HtunHlaAung.github.io/stickerminiapp"
VPS_URL      = "http://139.180.208.16:3000"
OWNER_ID     = "1849257766"
